In [1]:
# Perceptron
# A perceptron is a neural network with just one layer.
# It's a linear classifier that outputs a binary response variable.
# Consequently, the algorithm is called a "linear binary classifier".

In [2]:
# Linear Separability

# Data is said to have "linear separability" if it can be cleanly classified into one of two classes
# Data must be linearly separable inorder for a perceptron to operate properly.

In [3]:
# Four Essential Elements of a Perceptron

# 1) An input layer
# 2) Weights and bias
# 3) A weighted sum
# 4) An activation function

In [4]:
# Activation Function

# An activation function is a mathematical function that is deployed on each unit in a neural network.
# All units in a shared layer deploy the same activation function.
# The purpose of activation functions is to enable neural networks to model complex, nonlinear phenomenon.

# Types of activation function

# 1) Linear activation: tf.matmul() - single layer perceptron
# 2) Logistic sigmoid: use these often in the final output layer, useful with binary input features.
# 3) Threshold function: useful with binary features
# 4) ReLU (Rectified Linear Regression)
# 5) SoftMax

In [5]:
# Neural Network with a Perceptron

import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [7]:
from sklearn.linear_model import Perceptron

In [8]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [10]:
# Normalize the data

standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)
standardized_X_train = standardize.fit_transform(X_train)

In [12]:
standardized_X_test[0:10]

array([[ 0.45492158, -0.52342392,  0.74762942,  0.50642334],
       [-0.22746079, -0.91599186,  0.46935544,  0.36830789],
       [-0.63689021,  1.04684785, -1.03332404, -1.15096215],
       [-0.36393726, -1.50484378,  0.24673626,  0.09207697],
       [-0.09098432,  2.42083564, -1.03332404, -0.87473123],
       [ 0.3184451 , -1.89741172,  0.35804585, -0.04603849],
       [-1.59222552,  0.45799593, -1.08897884, -1.01284669],
       [-0.50041374,  1.43941579, -1.14463363, -0.87473123],
       [-0.50041374,  0.45799593, -0.92201445, -1.15096215],
       [ 0.59139805, -0.52342392,  0.52501024,  0.36830789]])

In [14]:
perceptron = Perceptron(max_iter=50, eta0=0.15,tol=1e-3,random_state=15)
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [15]:
y_pred = perceptron.predict(standardized_X_test)

In [16]:
print(y_test)
print(y_pred)

[1 1 0 1 0 1 0 0 0 1 0 1 2 1 1 0 0 2 1 0 0 2 2 0 0 1 2 2 0 2]
[2 1 0 1 0 1 0 0 0 1 0 1 2 2 1 0 0 2 1 0 0 2 2 0 0 2 2 2 0 2]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.70      0.82        10
           2       0.70      1.00      0.82         7

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.88        30
weighted avg       0.93      0.90      0.90        30

